# Generated by Django 5.0.6 on 2024-09-14 17:23

import django.db.models.deletion
from django.db import migrations, models

def update_chat_message_parents(apps, schema_editor):
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    ChatConversation = apps.get_model('chat', 'ChatConversation')

    for conversation in ChatConversation.objects.all():
        ghost_message = ChatMessage.objects.create(
            chat_conversation=conversation,
            role=None,
            content=None,
            user=conversation.user
        )

        messages = ChatMessage.objects.filter(chat_conversation=conversation).exclude(id=ghost_message.id).order_by('date_created')
        previous_message = ghost_message
        for message in messages:
            if message.parent is None:
                message.parent = previous_message
                message.save()
            previous_message = message

def reverse_chat_message_parents(apps, schema_editor):
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    ChatMessage.objects.all().update(parent=None)

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='chat.chatmessage'),
        ),
        migrations.RunPython(update_chat_message_parents, reverse_chat_message_parents),
    ]
