# Generated by Django 5.0.6 on 2024-08-29 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='provider',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
