# Generated by Django 5.0.6 on 2024-09-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='files',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
