# Generated by Django 5.0.6 on 2024-09-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='provider',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='ai_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.aimodel'),
        ),
    ]
