# Generated by Django 5.0.6 on 2024-09-16 11:48

from django.db import migrations

def update_chat_message_parents(apps, schema_editor):
    ChatMessage = apps.get_model('chat', 'ChatMessage')
    ChatConversation = apps.get_model('chat', 'ChatConversation')

    for conversation in ChatConversation.objects.all():
        ghost_message = ChatMessage.objects.create(
            chat_conversation=conversation,
            role=None,
            content=None,
            user=conversation.user
        )

        messages = ChatMessage.objects.filter(chat_conversation=conversation).exclude(id=ghost_message.id).order_by('date_created')
        previous_message = ghost_message
        for message in messages:
            if message.parent is None:
                message.parent = previous_message
                message.save()
            previous_message = message

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_chatmessage_parent_alter_chatmessage_content_and_more'),
    ]

    operations = [
        migrations.RunPython(update_chat_message_parents),
    ]
