# Generated by Django 5.0.6 on 2024-09-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_update_chat_message_parents'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='text', max_length=10),
        ),
    ]
