# Generated by Django 5.0.6 on 2024-09-28 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_aimodel_model_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
