# Generated by Django 5.0.6 on 2024-08-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_has_payment_method_user_stripe_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='stripe_customer_id',
            new_name='stripe_setup_intent',
        ),
    ]
