name: Deploy webapp on VPS
on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
        continue-on-error: false

      - name: Create frontend .env file
        run: |
          cp deployments/.env.frontend.prod frontend/.env
        continue-on-error: false

      - name: Install dependencies and build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
        continue-on-error: false

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: frontend/dist
        continue-on-error: false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        continue-on-error: false

      - name: Download frontend build artifacts
        uses: actions/download-artifact@v2
        with:
          name: frontend-build
          path: frontend/dist
        continue-on-error: false

      - name: Prepare VPS for deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/vezmir.ai.prod.new
            sudo mkdir -p /var/www/vezmir.ai.prod.new
            sudo chown -R ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_USERNAME }} /var/www/vezmir.ai.prod.new
            sudo chmod -R 755 /var/www/vezmir.ai.prod.new
        continue-on-error: false

      - name: Copy built frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "frontend/dist/*"
          target: "/var/www/vezmir.ai.prod.new"
          strip_components: 2
          overwrite: true
        continue-on-error: false

      - name: Set permissions for copied files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo chown -R ${{ secrets.VPS_USERNAME }}:www-data /var/www/vezmir.ai.prod.new
            sudo chmod -R 755 /var/www/vezmir.ai.prod.new
        continue-on-error: false

      - name: Prepare backend deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/azureuser/vezmir
            git pull origin ${{ github.head_ref }}
            git checkout ${{ github.head_ref }}
            rm -rf /home/azureuser/backend-prod.new
            cp -r /home/azureuser/vezmir/backend /home/azureuser/backend-prod.new
            cd /home/azureuser/backend-prod.new
            cp /home/azureuser/vezmir/deployments/.env.backend.prod .env
            echo "DJANGO_SECRET_KEY=$(openssl rand -base64 32)" >> .env
            echo "DJANGO_DATABSE_PASSWORD=${{ vars.DJANGO_DATABSE_PASSWORD }}" >> .env
            echo "OPENAI_API_KEY=${{ vars.OPENAI_API_KEY }}" >> .env
            echo "ANTHROPIC_API_KEY=${{ vars.ANTHROPIC_API_KEY }}" >> .env
            echo "GOOGLE_API_KEY=${{ vars.GOOGLE_API_KEY }}" >> .env
            echo "GROQ_API_KEY=${{ vars.GROQ_API_KEY }}" >> .env
            echo "STRIPE_PUBLISHABLE_KEY=${{ vars.STRIPE_PUBLISHABLE_KEY }}" >> .env
            echo "STRIPE_SECRET_KEY=${{ vars.STRIPE_SECRET_KEY }}" >> .env
            echo "DJANGO_GOOGLE_OAUTH2_CLIENT_ID=${{ vars.DJANGO_GOOGLE_OAUTH2_CLIENT_ID }}" >> .env
            echo "DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET=${{ vars.DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET }}" >> .env
            echo "DJANGO_GOOGLE_OAUTH2_PROJECT_ID=${{ vars.DJANGO_GOOGLE_OAUTH2_PROJECT_ID }}" >> .env
            echo "DJANGO_EMAIL_HOST_USER=${{ vars.DJANGO_EMAIL_HOST_USER }}" >> .env
            echo "DJANGO_EMAIL_HOST_PASSWORD=${{ vars.DJANGO_EMAIL_HOST_PASSWORD }}" >> .env
            source /home/azureuser/.prod-vezmir/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
        continue-on-error: false

      - name: Swap deployment directories and restart services
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo mv /var/www/vezmir.ai.prod /var/www/vezmir.ai.prod.old
            sudo mv /var/www/vezmir.ai.prod.new /var/www/vezmir.ai.prod
            sudo rm -rf /var/www/vezmir.ai.prod.old

            sudo mv /home/azureuser/backend-prod /home/azureuser/backend-prod.old
            sudo mv /home/azureuser/backend-prod.new /home/azureuser/backend-prod
            sudo rm -rf /home/azureuser/backend-prod.old

            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn
            sudo systemctl restart nginx
        continue-on-error: false
