name: Deploy webapp on VPS
on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # or your preferred Node.js version

      - name: Install dependencies and build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build

      - name: Copy built frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "frontend/dist/*"
          target: "/var/www/vezmir.ai.prod"
          strip_components: 2

      - name: Deploy backend to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/azureuser/vezmir
            git pull origin ${{ github.head_ref }}
            git checkout ${{ github.head_ref }}
            cp -r /home/azureuser/vezmir/backend/* /home/azureuser/backend-prod/
            cd /home/azureuser/backend-prod
            cp deployments/.env.backend.prod .env
            echo "DJANGO_SECRET_KEY=$(openssl rand -base64 32)" >> .env
            echo "DJANGO_DATABSE_PASSWORD=${{ secrets.DJANGO_DATABSE_PASSWORD }}" >> .env
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
            echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> .env
            echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> .env
            echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> .env
            echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> .env
            echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> .env
            echo "DJANGO_GOOGLE_OAUTH2_CLIENT_ID=${{ secrets.DJANGO_GOOGLE_OAUTH2_CLIENT_ID }}" >> .env
            echo "DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET=${{ secrets.DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET }}" >> .env
            echo "DJANGO_GOOGLE_OAUTH2_PROJECT_ID=${{ secrets.DJANGO_GOOGLE_OAUTH2_PROJECT_ID }}" >> .env
            echo "DJANGO_EMAIL_HOST_USER=${{ secrets.DJANGO_EMAIL_HOST_USER }}" >> .env
            echo "DJANGO_EMAIL_HOST_PASSWORD=${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}" >> .env
            source /home/azureuser/.prod-vezmir/bin/activate
            source /home/azureuser/.prod-vezmir/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
        continue-on-error: false

      - name: Swap deployment directories and restart services
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo mv /var/www/vezmir.ai.prod /var/www/vezmir.ai.prod.old
            sudo mv /var/www/vezmir.ai.prod.new /var/www/vezmir.ai.prod
            sudo rm -rf /var/www/vezmir.ai.prod.old

            sudo mv /home/azureuser/backend-prod /home/azureuser/backend-prod.old
            sudo mv /home/azureuser/backend-prod.new /home/azureuser/backend-prod
            sudo rm -rf /home/azureuser/backend-prod.old

            sudo systemctl daemon-reload
            sudo systemctl restart gunicorn

      - name: Restart Nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
        continue-on-error: false
