name: Deploy stage webapp on VPS
on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Stage
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        continue-on-error: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
        continue-on-error: false

      - name: Create frontend .env file
        run: |
          cp deployments/.env.frontend.stage frontend/.env
        continue-on-error: false

      - name: Install dependencies and build frontend
        working-directory: ./frontend
        run: |
          npm ci
          npm run build
        continue-on-error: false

      - name: Upload frontend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist
          include-hidden-files: true
        continue-on-error: false

      - name: Create backend .env file
        run: |
          cp deployments/.env.backend.stage backend/.env.temp
          echo "DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}" >> backend/.env.temp
          echo "DJANGO_DATABSE_PASSWORD=${DJANGO_DATABSE_PASSWORD}" >> backend/.env.temp
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> backend/.env.temp
          echo "ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}" >> backend/.env.temp
          echo "GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}" >> backend/.env.temp
          echo "GROQ_API_KEY=${{ secrets.GROQ_API_KEY }}" >> backend/.env.temp
          echo "STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}" >> backend/.env.temp
          echo "STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}" >> backend/.env.temp
          echo "DJANGO_GOOGLE_OAUTH2_CLIENT_ID=${{ secrets.DJANGO_GOOGLE_OAUTH2_CLIENT_ID }}" >> backend/.env.temp
          echo "DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET=${{ secrets.DJANGO_GOOGLE_OAUTH2_CLIENT_SECRET }}" >> backend/.env.temp
          echo "DJANGO_GOOGLE_OAUTH2_PROJECT_ID=${{ secrets.DJANGO_GOOGLE_OAUTH2_PROJECT_ID }}" >> backend/.env.temp
          echo "DJANGO_EMAIL_HOST_USER=${{ secrets.DJANGO_EMAIL_HOST_USER }}" >> backend/.env.temp
          echo "DJANGO_EMAIL_HOST_PASSWORD=${DJANGO_EMAIL_HOST_PASSWORD}" >> backend/.env.temp
        env:
          DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}
          DJANGO_DATABSE_PASSWORD: ${{ secrets.DJANGO_DATABSE_PASSWORD }}
          DJANGO_EMAIL_HOST_PASSWORD: ${{ secrets.DJANGO_EMAIL_HOST_PASSWORD }}
        continue-on-error: false

      - name: Upload backend build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: backend-dir
          path: backend
          include-hidden-files: true
        continue-on-error: false

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        continue-on-error: false

      - name: Download frontend build artifacts
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/dist
        continue-on-error: false

      - name: Prepare VPS for deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/dev.vezmir.ai.new
            sudo rm -rf /home/azureuser/backend-dev.vezmir.ai.new
            sudo mkdir -p /var/www/dev.vezmir.ai.new
            sudo chown -R ${{ secrets.VPS_USERNAME }}:${{ secrets.VPS_USERNAME }} /var/www/dev.vezmir.ai.new
            sudo chmod -R 755 /var/www/dev.vezmir.ai.new
        continue-on-error: false

      - name: Copy built frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "frontend/dist/*"
          target: "/var/www/dev.vezmir.ai.new"
          strip_components: 2
          overwrite: true
        continue-on-error: false

      - name: Set permissions for copied files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo chown -R ${{ secrets.VPS_USERNAME }}:www-data /var/www/dev.vezmir.ai.new
            sudo chmod -R 755 /var/www/dev.vezmir.ai.new
        continue-on-error: false

      - name: Download backend build artifacts
        uses: actions/download-artifact@v4
        with:
          name: backend-dir
          path: backend
        continue-on-error: false

      - name: Copy backend to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "backend/*"
          target: "/home/azureuser/backend-dev.vezmir.ai.new"
          strip_components: 1
        continue-on-error: false

      - name: Install dependencies and migrate
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            source /home/azureuser/.stage-vezmir/bin/activate
            cd /home/azureuser/backend-dev.vezmir.ai.new
            mv .env.temp .env
            pip install -r requirements.txt
            python manage.py migrate
            if [ $? -ne 0 ]; then
              echo "Migration failed"
              exit 1
            fi
            python manage.py loaddata fixtures/models
            deactivate
        continue-on-error: false

      - name: Swap deployment directories
        if: success()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo mv /var/www/dev.vezmir.ai /var/www/dev.vezmir.ai.old
            sudo mv /home/azureuser/backend-dev.vezmir.ai /home/azureuser/backend-dev.vezmir.ai.old

            sudo mv /var/www/dev.vezmir.ai.new /var/www/dev.vezmir.ai
            sudo mv /home/azureuser/backend-dev.vezmir.ai.new /home/azureuser/backend-dev.vezmir.ai
        continue-on-error: false

      - name: Deployment failed
        if: failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            if [ -d /var/www/dev.vezmir.ai.old ]; then
              sudo mv /var/www/dev.vezmir.ai.old /var/www/dev.vezmir.ai
            fi
            if [ -d /home/azureuser/backend-dev.vezmir.ai.old ]; then
              sudo mv /home/azureuser/backend-dev.vezmir.ai.old /home/azureuser/backend-dev.vezmir.ai
            fi
            source /home/azureuser/.stage-vezmir/bin/activate
            cd /home/azureuser/backend-dev.vezmir.ai
            pip install -r requirements.txt
            python manage.py migrate
            deactivate

      - name: Restart services and clean up old deployment directories
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST_STAGE }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo rm -rf /var/www/dev.vezmir.ai.old
            sudo rm -rf /home/azureuser/backend-dev.vezmir.ai.old

            sudo systemctl daemon-reload
            sudo systemctl reload gunicorn-stage
            sudo systemctl reload nginx
